### ISSUE TITLE
How do you get zoneIDs for a given zone?

### ISSUE THREAD

**Issue by kaydiechii** [CalumMagee/reminder-plugin#2]
I'm unable to find any lists or any easy way to get information on how to actually functionally use this plugin - im very interested in using it, specifically for certain things like not having the right item when entering the TOA loot room, getting itemID is trivial, but how do you get a zoneID?

**Comment by LuxOG** [comment]
Unfortunately it is a bit of a pain. The only way I know of is to run runelite on developer mode and use the dev tools to get your region ID while standing in that location.

**Comment by RedSparr0w** [comment]
You can use https://explv.github.io/  with `region grid` and `region labels` enabled.
